package test.model;

/**
 * Database Table Remarks:
 *   权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_privilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysPrivilege {
    /**
     * Database Column Remarks:
     *   权限 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_privilege.privilege_name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   权限 URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_privilege.privilege_url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_privilege.sys_privilege_id
     *
     * @return the value of t_sys_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_privilege.sys_privilege_id
     *
     * @param id the value for t_sys_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_privilege.privilege_name
     *
     * @return the value of t_sys_privilege.privilege_name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_privilege.privilege_name
     *
     * @param name the value for t_sys_privilege.privilege_name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_privilege.privilege_url
     *
     * @return the value of t_sys_privilege.privilege_url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_privilege.privilege_url
     *
     * @param url the value for t_sys_privilege.privilege_url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }
}