package test.model;

/**
 * Database Table Remarks:
 *   角色权限关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_role_privilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysRolePrivilege {
    /**
     * Database Column Remarks:
     *   角色 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_privilege.sys_role_id
     *
     * @mbggenerated
     */
    private Long sysRoleId;

    /**
     * Database Column Remarks:
     *   权限 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    private Long sysPrivilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_privilege.sys_role_id
     *
     * @return the value of t_sys_role_privilege.sys_role_id
     *
     * @mbggenerated
     */
    public Long getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_privilege.sys_role_id
     *
     * @param sysRoleId the value for t_sys_role_privilege.sys_role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_privilege.sys_privilege_id
     *
     * @return the value of t_sys_role_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    public Long getSysPrivilegeId() {
        return sysPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_privilege.sys_privilege_id
     *
     * @param sysPrivilegeId the value for t_sys_role_privilege.sys_privilege_id
     *
     * @mbggenerated
     */
    public void setSysPrivilegeId(Long sysPrivilegeId) {
        this.sysPrivilegeId = sysPrivilegeId;
    }
}