package test.model;

/**
 * Database Table Remarks:
 *   用户角色关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_user_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysUserRole {
    /**
     * Database Column Remarks:
     *   用户 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.sys_user_id
     *
     * @mbggenerated
     */
    private Long sysUserId;

    /**
     * Database Column Remarks:
     *   角色 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.sys_role_id
     *
     * @mbggenerated
     */
    private Long sysRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.sys_user_id
     *
     * @return the value of t_sys_user_role.sys_user_id
     *
     * @mbggenerated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.sys_user_id
     *
     * @param sysUserId the value for t_sys_user_role.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.sys_role_id
     *
     * @return the value of t_sys_user_role.sys_role_id
     *
     * @mbggenerated
     */
    public Long getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.sys_role_id
     *
     * @param sysRoleId the value for t_sys_user_role.sys_role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
    }
}